# Generated by Django 5.2.8 on 2025-11-24 09:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockItem',
            fields=[
                ('livestock_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('warning', 'Warning'), ('sick', 'Sick'), ('verified', 'Verified')], default='healthy', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('listing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_for_sale', models.BooleanField(default=False)),
                ('current_location', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('pending', 'Pending'), ('hidden', 'Hidden')], default='available', max_length=20)),
                ('breed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestock_items', to='livestock.breed')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_items', to='accounts.farmer')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livestock_items', to='livestock.livestockspecies')),
            ],
        ),
        migrations.CreateModel(
            name='IoTDeviceData',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('activity_level', models.FloatField(blank=True, null=True)),
                ('battery_level', models.FloatField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=120, null=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_data', to='livestock.livestockitem')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.farmer')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='livestock.livestockitem')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='livestock.livestockspecies'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='accounts.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductListing',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('listing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_category', models.CharField(blank=True, max_length=120, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_listings', to='accounts.farmer')),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_listings', to='livestock.livestockitem')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('order_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='livestock.livestockitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='livestock.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='livestock.productlisting')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='breed',
            unique_together={('species', 'breed_name')},
        ),
    ]
