# Generated by Django 5.2.8 on 2025-12-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='livestock_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='livestock.livestockitem')),
            ],
        ),
    ]
