# Generated by Django 6.0 on 2025-12-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestockitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('hidden', 'Hidden')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('inquiry_sent', 'Inquiry Sent (Waiting for Farmer)'), ('approved', 'Order Approved (Preparing for Delivery)'), ('completed', 'Delivered & Paid'), ('cancelled', 'Cancelled')], default='inquiry_sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pay_on_delivery', 'Pay on Delivery'), ('paid', 'Paid')], default='pay_on_delivery', max_length=20),
        ),
    ]
