# Generated by Django 6.0 on 2025-12-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_alter_livestockitem_status_alter_order_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending (In Cart)'), ('inquiry_sent', 'Inquiry Sent (Waiting for Farmer)'), ('approved', 'Order Approved (Ready for Payment/Delivery)'), ('confirmed', 'Completed (Paid & Delivered)'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
