# Generated by Django 6.0 on 2025-12-13 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Phone number for delivery coordination', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Where should this be delivered?', null=True),
        ),
    ]
